version: '3'
services:
  producer-consumer:
    image: asarkar/ufo-sightings-akka:1.0-SNAPSHOT
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      FROM_YEAR_MONTH: 2016-01
#  consumer:
#    image: asarkar/ufo-sightings-spark:1.0-SNAPSHOT
#    depends_on:
#      - kafka
#    environment:
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    ports:
#      - "4040:4040"
  kafka:
    image: asarkar/kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092